name: .NET Core Desktop for Windows

on:
  push:
    branches: [ "cl" ]
  pull_request:
    branches: [ "cl" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: SIT.Manager.Avalonia.Desktop
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Get build date
      id: build
      shell: pwsh
      run: |
        $CurrentTime = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        Write-Output "NOW=$CurrentTime" >> $env:GITHUB_OUTPUT
        
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --property:Version=${{ steps.build.outputs.NOW }}
      
    - name: Package File
      run: Compress-Archive -Path D:\a\SIT.Manager.Avalonia\SIT.Manager.Avalonia\SIT.Manager.Desktop\bin\${{ matrix.configuration }}\net8.0\win-x64\* -Destination ${{ matrix.configuration }}.zip
      
    - name: Upload Built Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: |
          ${{ matrix.configuration }}.zip